apiVersion: batch/v1
kind: Job
metadata:
  name: religion-rule-sandbox
  labels:
    edu.web3/plugin-id: edu.global.sandbox.religion
    edu.web3/compliance: fabric-sandbox-only
spec:
  template:
    metadata:
      labels:
        edu.web3/plugin-id: edu.global.sandbox.religion
    spec:
      restartPolicy: Never
      containers:
        - name: runner
          image: hyperledger/fabric-tools:2.5
          env:
            - name: CHAIN_ID
              value: fabric-local
            - name: EDU_NAMESPACE
              value: ns-domain-global
            - name: EDU_TASK_TYPE
              value: GLOBAL_RELIGION_RULE_SANDBOX
